@extends('frontend.layout.frontmain')
@section('content')
<div class="content-wrapper">
    <div class="container">
    @if(session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
        @endif

        <h1 class="text-center">Blog enquiry generated by user</h1>
        <h2 class="text-center" style="float:left">View All enquiry</h2>
        
        
        
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>E-mail</th>
                    <th>Subject</th>
                    <th>Message</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($conn as $connect)
                <tr>
                    <td>{{ $connect->id }}</td>
                    <td>{{ $connect->name }}</td>
                    <td>{{ $connect->email }}</td>
                    <td>{{ $connect->subject }}</td>
                    <td>{{ $connect->message }}</td>
                    <td>
                        
                        <a href="#" class="btn btn-success"><i class='fas fa-edit'></i></a>
                        
                       
                        <a href="#" class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i></a>
                        
                       
                        <!--a href="#" class="btn btn-warning"><i class="fas fa-eye"></i> </!--a-->
                       
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection